config/routes.rb
Rails.application.routes.draw do
  
  resources :users
  root "articles#home"
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, expect: [:new]
  get 'login', to: 'sessions#new'
  post 'login', to:'sessions#create'
  delete 'logout', to:'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    belongs_to :user
    validates :title, presence: true , length: {minimum: 6, maximum: 100}
    validates :desc, presence: true ,  length: {minimum: 10, maximum: 100}
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    has_many :articles
    validates :username, presence: true ,
                        uniqueness:  {case_sensitive: false}, 
                        length: {minimum: 3 , maximum: 25};
   
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true ,
                        uniqueness: {case_sensitive: false},
                        length: {maximum: 125},
                        format: {with: VALID_EMAIL_REGEX};

    has_secure_password

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit ,:destroy, :update]
    def show
    end
    def index
        @articles = Article.all
    end
    def new
        @article = Article.new
    end
    def edit 
    end
    def update
        if  @article.update(article_params)
            flash[:notice] ="Article updated sucessfuly"
            redirect_to @article
        else
            render 'edit'
        end
    end
    def create
        @article =  Article.new(article_params)
        @article.user = User.first
        #render plain: @article.inspect
        if  @article.save
            flash[:notice] ="Article created sucessfuly"
            redirect_to @article
        else
            render 'new'
        end
    end
    def destroy
        @article.destroy
        redirect_to articles_path
    end
    def home
        
    end
    private 
        def set_article
            @article = Article.find(params[:id])
        end
        def article_params
            params.require(:article).permit(:title, :desc)
        end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate( params[:session][:password])
            session[:user_id] = user.id
            flash[:notice] = "Login sucess"
            redirect_to user
        else
            flash.now[:alert ]= "Wrong details"
            render 'new'
        end

    end
    def destroy
        session[:user_id] = nil
        flash[:notice] = "Logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user= User.new
    end
    def create
        @user = User.new(user_params)
        if @user.save
            flash[:notice] = "Signup sucessful wel come to Article #{@user.username}"
            redirect_to articles_path
        else
            render 'new'
        end
    end
    def edit
        @user = User.find(params[:id])
    end
    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:notice] = "Update sucessful to profile  Of  #{@user.username}"
            redirect_to articles_path
        else
            render 'edit'
        end
    end
    def show
        @user = User.find(params[:id])
        @articles = @user.articles
    end
    def index
        @users = User.all
    end
    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_article.html.erb
<%= @articles.each do |article|%>
<div class="card-body">
            <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-success" %></h5>
            <p class="card-text"><%= truncate(article.desc, length: 100) %></p>
            <%= link_to "View", article_path(article), class: "btn btn-outline-success" %>
            <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-info" %>
            <%= link_to "Delete", article_path(article), class: "btn btn-outline-danger", method: :delete, data: {confirm: "Are you sure?"} %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
            edited <%= time_ago_in_words(article.updated_at) %> ago</small>
          </div>
<%end%>

app/views/articles/_error.html.erb
<% if @article.errors.any?%>
<h2>Correct these errors </h2>
    <ul>
        <% @article.errors.full_messages.each do |msg|%>
            <li><%= msg%></li>
        <%end%>
    </ul>
<%end%>

app/views/articles/_form.html.erb
<%= render 'shared/error', obj: @article%>
<%= form_with(model: @article, local: true)  do |f| %>
<p>
    <%= f.label :title%><br/>
    <%= f.text_field :title%>

</p>
<p>
    <%= f.label :desc%>
    <br/>
    <%= f.text_area :desc%>

</p>
<p>
    <%= f.submit %>
</p>

<%end%>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= render 'form'%>

<%= link_to 'Return' , articles_path%>

app/views/articles/home.html.erb
<div class="container" id="home-container">
<div class="jumbotron text-center text-white">
  <h1 class="display-4">Hello, world!</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <a class="btn btn-success btn-lg" href="#" role="button">Learn more</a>
</div>
</div>

app/views/articles/index.html.erb
<h1>List Articles</h1>

<table>
<thead>
<tr>
<th>Title</th>
<th>Desc</th>
<th>User</th>
<th colsapn="3">Actions</th>
</tr>
</thead>
<tbody> 
<% @articles.each do |article|%>
<tr>
<td><%=article.title%></td>
<td><%=article.desc%></td>
<td><%=article.user.username if article.user%></td>
<td><%= link_to 'Show', article_path(article)%></td>
<td><%= link_to 'Edit', edit_article_path(article)%></td>
<td><%= link_to 'Delete', article_path(article), method: :delete,data: {confirm: "Are you sure?"}%></td>

</tr>
<%end%>
</tbody>


</table>
<p>
<%= link_to 'Create new Article', new_article_path%>
</p>

app/views/articles/new.html.erb
<h1>Create Article</h1>

<%= render 'form'%>
<%= link_to 'Return' , articles_path%>

app/views/articles/show.html.erb
<h1>Show Articles</h1>
<p><strong>User:</strong> <%=@article.user.username =%></p>
<p><strong>Title: </strong><%=@article.title =%></p>
<p><strong>Desc: </strong><%=@article.desc=%></p>

<%= link_to 'Edit', edit_article_path(@article)%>
||
<%=link_to 'Delete',article_path(@article),method: :delete, data: {confirm: "Are you sure?"}%> ||
<%= link_to 'Return' , articles_path%>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
      <%=msg%>
<%end%>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" id="logo" href="#">ALPHA BLOG</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
 
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
      <%= link_to 'Logout', logout_path ,method: :delete%>
          </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar'%>
    <%= render 'layouts/messages'%>
    <%= yield %>
  </body>
</html>

app/views/shared/_error.html.erb
<% if obj.errors.any?%>
<h2>Correct these errors </h2>
    <ul>
        <% obj.errors.full_messages.each do |msg|%>
            <li><%= msg%></li>
        <%end%>
    </ul>
<%end%>

app/views/users/_form.html.erb
<%= render 'shared/error', obj: @user%>
<%= form_with(model: @user, local: true)  do |f| %>
<p>
    <%= f.label :username%><br/>
    <%= f.text_field :username%>

</p>
<p>
    <%= f.label :email%>
    <%= f.email_field :email%>

</p>
<p>
    <%= f.label :password%>
    <%= f.password_field :password%>

</p>
<p>
    <%= f.submit(@user.new_record? ?  "SignUp" : "Update Account")%>
</p>

<%end%>

app/views/users/edit.html.erb
<h1>Edit for profil</h1>
<%= render 'form'%>

app/views/users/index.html.erb
<h1>List of all our members</h1>

<%= @users.each do |user|%>
<div class="card-body">
            <h5 class="card-title"><%= link_to user.username, user_path(user), class: "text-success" %></h5>
            <p class="card-text"><%= user.email %></p>
            <p class="card-text"><%=pluralize(user.articles.count,'article')%>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(user.created_at) %> ago, 
            edited <%= time_ago_in_words(user.updated_at) %> ago</small>
          </div>
<%end%>

app/views/users/new.html.erb
<h1>Signup for Article</h1>
<%= render 'form'%>

app/views/users/show.html.erb
<h1><%= @user.username%>'s profile</h1>
<h3>Articles by <%= @user.username%></h3>
<%= render 'articles/article' %>